// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
    SignInForm: typeof import('./src/components/login/SignInForm.vue')['default']
    SignUpForm: typeof import('./src/components/login/SignUpForm.vue')['default']
  }
}

export { }
