// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DraggableArea: typeof import('./src/components/prototype/DraggableArea.vue')['default']
    ForgetForm: typeof import('./src/components/login/ForgetForm.vue')['default']
    GlobalContent: typeof import('./src/components/common/GlobalContent.vue')['default']
    GlobalSidebar: typeof import('./src/components/common/GlobalSidebar.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
<<<<<<< HEAD
    PasswordChange: typeof import('./src/components/user/PasswordChange.vue')['default']
    PersonInfo: typeof import('./src/components/user/PersonInfo.vue')['default']
=======
    ProjectList: typeof import('./src/components/project/ProjectList.vue')['default']
    RecentProject: typeof import('./src/components/project/RecentProject.vue')['default']
>>>>>>> dev
    SignInForm: typeof import('./src/components/login/SignInForm.vue')['default']
    SignUpForm: typeof import('./src/components/login/SignUpForm.vue')['default']
    Vditor: typeof import('./src/components/document/Vditor.vue')['default']
    WorkSpace: typeof import('./src/components/prototype/WorkSpace.vue')['default']
  }
}

export { }
